# Generated by Django 5.1.7 on 2025-04-18 21:48

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('domesticated', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('adoption_status', models.BooleanField()),
                ('pet_type', models.CharField(choices=[(1, 'Dog'), (2, 'Cat'), (3, 'Bird')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('shelter_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('website_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Favourite', models.BooleanField(verbose_name=api.models.Pet)),
                ('AdoptionUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pet')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('application_status', models.BooleanField(auto_created=True)),
                ('application_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('adopter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateTimeField(auto_now_add=True)),
                ('adoption_status', models.BooleanField(default=False)),
                ('adopter_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='shelter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shelter'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('fundId', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('adopter_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shelter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='ShelterManagement',
            fields=[
                ('manage_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.adminuser')),
                ('shelter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
