# Generated by Django 5.1.7 on 2025-04-19 22:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pet_shelter_adminuser_adoptionapplication_adopter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetTest',
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sheltermanagement',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sheltermanagement',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='application_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='adoption_status',
            field=models.TextField(blank=True, choices=[('Available', 'Available'), ('Adopted', 'Adopted')], default='Available', null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(blank=True, choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Rabbit', 'Rabbit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='shelter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='api.shelter'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sheltermanagement',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sheltermanagement',
            name='admin_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='managed_shelters', to='api.adminuser'),
        ),
        migrations.AlterField(
            model_name='sheltermanagement',
            name='shelter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management', to='api.shelter'),
        ),
    ]
