# Generated by Django 5.1.7 on 2025-04-20 07:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pet_shelter_adminuser_adoptionapplication_adopter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.adminuser'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='adoption_status',
            field=models.TextField(blank=True, choices=[(1, 'Available'), (2, 'Adopted')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[(1, 'Male'), (2, 'Female')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(blank=True, choices=[(1, 'Dog'), (2, 'Cat'), (3, 'Bird'), (4, 'Rabbit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='shelter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='api.shelter'),
        ),
    ]
