# Generated by Django 5.1.7 on 2025-04-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_pettest_pet_image_shelter_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheltermanagement',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sheltermanagement',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='sheltermanagement',
            name='website_url',
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
