# Generated by Django 5.1.7 on 2025-04-19 23:58

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sheltermanagement_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheltermanagement',
            name='admin_user',
            field=models.ForeignKey(default=api.models.get_root_admin_user, on_delete=django.db.models.deletion.CASCADE, related_name='managed_shelters', to=settings.AUTH_USER_MODEL),
        ),
    ]
