# Generated by Django 5.1.7 on 2025-04-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionapplication',
            old_name='pet_id',
            new_name='pet',
        ),
        migrations.AlterField(
            model_name='pet',
            name='adoption_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Adopted', 'Adopted')], default='Available', max_length=10),
        ),
    ]
