# Generated by Django 5.1.7 on 2025-04-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_pet_id_adoptionapplication_pet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
