version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME:-adoptify}
      MYSQL_USER: ${DB_USER:-adoptify_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-adoptify_pw}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/sql:/docker-entrypoint-initdb.d/ # Mount SQL directory
    networks:
      - adoptify_network

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/adoptify_backend/.env.${DJANGO_ENV:-development}  # Dynamically load environment file based on the DJANGO_ENV variable
    depends_on:
      - db
    networks:
      - adoptify_network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - adoptify_network

volumes:
  mysql_data:

networks:
  adoptify_network:
    driver: bridge
